version: '2.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: nefu
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nefu
      POSTGRES_USER: nefu
      POSTGRES_PASSWORD: nefu
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres: