services:
    telegrambot:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                MOD: 'Debug'
        ports:
        - '0.0.0.0:5000:5000'
        environment:
            ASPNETCORE_URLS: 'http://+:5000'
            Database__Host: 'db'
        restart: on-failure
        links:
        - db
    db:
        ports:
              - "5433:5432"
        restart: always
        environment:
          - POSTGRES_PASSWORD=Qwerty123!
          - POSTGRES_USER=postgres
        image: postgres